jwt:
  secret: secret-value

server:
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizza-store
    username: admin
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    web: TRACE

springdoc:
  show-actuator: true