jwt:
  secret: secret-value

spring:
  datasource:
    url: jdbc:postgresql://postgres-database:5432/pizza-store
    username: admin
    password: secret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect